name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm ci

      - name: Lancer les tests avec couverture
        # --run force l'exécution en mode CI, --coverage génère le rapport
        run: npm test -- --run --coverage

      - name: Publier le rapport de couverture
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage 